config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/about', to: "home#about", as:'about'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :books
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	validates :title,presence: true
	validates :body,presence: true,length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: {minimum: 2,maximum: 20},presence: true
  validates :int, length: {maximum: 50}

  has_many :books,dependent: :destroy
  attachment :profile_image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	#before_action :authenticate_user!

	protected

	def after_sign_in_path_for(resource)
  		user_path(current_user)
	end

	def after_sing_out_path_for(resource)
		root_path
	end

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys:[:name,:email])
		devise_parameter_sanitizer.permit(:sing_in, keys:[:name,])
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
		before_action :authenticate_user!
		before_action :correct_user, only: [:edit, :update]
	def new
	end

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
			flash[:notice] = "successfully"
		redirect_to book_path(@book)
		else
			flash[:notice] = "error"
			@user = current_user
			@book = Book.new
			@books = Book.all
			render action: :index
		end
	end

	def index
		@book = Book.new
		@books = Book.all
		@user = current_user
	end

	def show
		@books = Book.find(params[:id])
		@book = Book.new
		@user = current_user
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end

	def edit
		@book = Book.find(params[:id])
		#@user = current_user
		#@books = @user.books
		#if @books != @book
			#redirect_to user_path(current_user)
		#end
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
		flash[:notice] = "successfully"
		redirect_to book_path(@book)
		else
			flash[:notice] = "error"
			render action: :edit
		end
	end

	#def correct_user
  	#@micropost = current_user.microposts.find(params[:id])
    	#unless
    		#@micropost
      	#redirect_to root_url
    	#end
	#end

	private
		def book_params
			params.require(:book).permit(:title,:body)
		end

		def correct_user
			book = Book.find(params[:id])
			if current_user.id != book.user.id
			redirect_to books_path
		end
		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def show
  	@book = Book.new
  	@user = User.find(params[:id])
  	#@book = Book.where(:user_id, @user.id)
  	@books = @user.books
  end
  def index
  	@book = Book.new
  	@user = current_user
    @users = User.all
    #@user = User.find(params[:id])
  end
  def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		@book.save
		redirect_to books_path
	end

  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "successfully"
      redirect_to user_path(@user.id)
    else
      flash[:notice] = "error"
      render action: :edit
    end
  end

  #def correct_user
    #@micropost = current_user.microposts.find(params[:id])
      #unless
        #@micropost
        #redirect_to root_url
      #end
  #end

private
		def book_params
			params.require(:book).permit(:title,:body,:user_id,)
		end
    def user_params
      params.require(:user).permit(:name, :profile_image, :int)
    end

    def correct_user
      user = User.find(params[:id])
      if user != current_user
      redirect_to books_path
    end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if flash[:notice] %>
	<p><%= flash[:notice] %></p>
<% end %>
<%= form_for(@book) do |f| %>

			<h4>title</h4>
			<%= f.text_field :title, class: "book_title"%>

			<h4>body</h4>
			<%= f.text_area :body, class: "book_body"%>

			<p><%= f.submit '保存' %></p>
<% end %>
	<%= link_to "Back" ,books_path, class: "back" %>

app/views/books/index.html.erb
<% if flash[:notice] %>
	<p><%= flash[:notice] %></p>
<% end %>
<div class="container">
	<div class="row">
		<div class="col-lg-4">
		<h2>User info</h2>
		<br><%= @user.name %></br>
		<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg',fallback: "no_image.jpg" %>
		<br><%= link_to "プロフィール編集", edit_user_path(@user),class: "edit_user_#{@user.id}" %></br>
		<br><%= @user.int %></br>
		<h2>New book</h2>
		<%= form_for(@book) do |f| %>

			<h4>title</h4>
			<%= f.text_field :title, class: "book_title" %>

			<h4>body</h4>
			<%= f.text_area :body, class: "book_body" %>

			<p><%= f.submit 'createbook' %></p>
		<% end %>
		</div>
		<div class="col-lg-8">
			<table class="table">
			<thead>
				<th>image</th>
				<th>title</th>
				<th>body</th>
			</thead>
		<% @books.each do |book| %>
			<tbody>
			<td><%= link_to user_path(book.id) ,class: "user" do %>
			<%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg',fallback: "no_image.jpg" %>
				<% end %></td>
			<td><%= link_to book.title,book_path(book.id),class: "book_#{book.id}" %></td>
			<td><%= book.body %></td>
			<% end %>
			</tbody>
		</div>
	</table>
	</div>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
	<p><%= flash[:notice] %></p>
<% end %>
<div class="container">
	<div class="row">
		<div class="col-lg-4">
		<h2>User info</h2>
		<br><%= @user.name %></br>
		<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg',fallback: "no_image.jpg" %>
		<br><%= link_to "プロフィール編集", edit_user_path(@user),class: "edit_user_#{@user.id}" %></br>
		<br><%= @user.int %></br>
		<h2>New book</h2>
		<%= form_for(@book) do |f| %>

			<h4>title</h4>
			<%= f.text_field :title, class: "book_title" %>

			<h4>body</h4>
			<%= f.text_area :body, class: "book_body" %>

			<p><%= f.submit 'createbook' %></p>
		<% end %>
	</div>
<div class="col-lg-8">
			<table class="table">
			<thead>
				<th>title</th>
				<th>body</th>
			</thead>

			<tbody>
				<td><%= @books.title %></td>
				<td><%= @books.body %></td>
			<% if @books.user == current_user %>
				<td><%= link_to "delete", book_path(@books), method: :delete,class: "destroy_book_#{@books.id}" %></td>
				<td><%= link_to "edit", edit_book_path(@books),class: "edit_book_#{@books.id}" %></td>
			<% end %>
			</tbody>
		</table>
</div>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/index.html.erb
 <br><span class="glyphicon glyphicon-asterisk" aria-hidden="true"><%= link_to "サインアップ", new_user_registration_path,class: "sign_up" %></span></br>
 <span class="glyphicon glyphicon-search" aria-hidden="true"><%= link_to "ログイン", new_user_session_path,class: "sign_in" %></span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<% if user_signed_in? %>
      <li class="nav nav-tabs">
        <%= link_to "ホーム", user_path(current_user), class: "home" %>
        <%= link_to "ログアウト", destroy_user_session_path,class: "logout", method: :delete %>
        <%= link_to 'Book', books_path,class: "books" %>
        <%= link_to 'Users', users_path,class: "users" %>
      </li>
    <% else %>
      <li class="nav nav-tabs">
        <%= link_to "サインアップ", new_user_registration_path,class: "sign_up" %>
        <%= link_to "ログイン", new_user_session_path,class: "sign_in" %>
        <%= link_to "ホーム",home_index_path,class: "home" %>
        <%= link_to "アバウト",about_path,class: "about" %>
      </li>
    <% end %>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<% if flash[:notice] %>
	<p><%= flash[:notice] %></p>
<% end %>
<%= form_for(@user) do |f| %>
    <div class="form-group has-icon">
        <label class="control-label sr-only" for="inputEmail">Name</label>
        <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前",class: "name" %>
        <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
    </div>

    <%= f.text_field :int,class: "introduction" %>
<div class="form-group has-icon">

    <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user_image",class: "user_image" %>
</div>
    <%= f.submit "変更を保存", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
<% end %>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-4">
			<h2>User info</h2>
			<%= @user.name %><br>
			 <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg',fallback: "no_image.jpg" %>
			<br><%= link_to "プロフィール編集", edit_user_path(@user),class: "edit_user_#{@user.id}" %></br>
			<br><%= @user.int %></br>
		<h2>New book</h2>
		<%= form_for(@book) do |f| %>

			<h4>title</h4>
			<%= f.text_field :title, class: "book_title"%>

			<h4>body</h4>
			<%= f.text_area :body, class: "book_body"%>

			<p><%= f.submit 'createbook' %></p>
		<% end %>
		</div>
		<div class="col-lg-8">
			<table class="table">
			<thead>
				<th>image</th>
				<th>name</th>
			</thead>
		<% @users.each do |user| %>
			<tbody>
			<td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg',fallback: "no_image.jpg" %></td>
			<td><%= user.name %></td>
			<td><%= link_to "show", user_path(user.id),class: "user_#{user.id}" %>
			<% end %>
			</tbody>
		</div>
	</table>
	</div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
	<p><%= flash[:notice] %></p>
<% end %>
<div class="container">
	<div class="row">
		<div class="col-lg-4">
			<h2>User info</h2>
		<br><%= @user.name %></br>
		<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg',fallback: "no_image.jpg" %>
		<br><%= link_to "プロフィール編集", edit_user_path(@user),class: "edit_user_#{@user.id}" %></br>
		<br><%= @user.int %></br>
		<h2>New book</h2>
		<%= form_for(@book) do |f| %>

			<h4>title</h4>
			<%= f.text_field :title, class: "book_title"%>

			<h4>body</h4>
			<%= f.text_area :body, class: "book_body"%>

			<p><%= f.submit 'createbook' %></p>
		<% end %>
		</div>
		<div class="col-lg-8">
			<table class="table">
			<thead>
				<th>title</th>
				<th>body</th>
			</thead>
		<% @books.each do |book| %>
			<tbody>
			<td><%= link_to book.title,book_path(book.id),class: "book_#{book.id}" %></td>
			<td><%= book.body %></td>
			<% end %>
			</tbody>
		</div>
	</table>
	</div>
</div>